Update README.md
w3c/w3c-website pull request #507
Opened 2023-09-20 16:50 UTC by simonrjones

- Update the README to make feedback instructions simpler for new users
- Add link to the feedback email address

2023-09-22 07:14 UTC, vivienlacourba requested changes

2023-09-22 07:14 UTC, vivienlacourba commented on README.md
> +We welcome feedback from the community. You can submit feedback or issues via GitHub or  email.
```suggestion
We welcome feedback from the community. You can submit feedback or issues via GitHub or email.
```

2023-09-22 07:14 UTC, vivienlacourba commented on README.md
> +This GitHub repo is used to manage feedback and bug reports for the W3C website redesign project.
```suggestion
This GitHub repo is used to manage feedback and bug reports for the W3C website.
```

2023-09-22 07:14 UTC, vivienlacourba commented on README.md
> +The [design system](https://design-system.w3.org/) contains accessible HTML/CSS templates and components for use when creating W3C websites.
```suggestion
The [design system](https://design-system.w3.org/) contains accessible HTML/CSS templates and components for use when creating W3C websites.
```

2023-09-23 15:49 UTC, vivienlacourba approved these changes

2023-09-23 15:50 UTC, merged

2023-10-07 05:00 UTC, Ufvkim121212 reviewed
Este software no  lo puedes copiar ni usar o vender sin la autorización de JOSE ANDRES MIRANDA ORTEGA  soy el dueño de todos los artículos que que usan la red como alohamiento y arranque sofwer IP web framewerd  y actualmente incluí a mi software varias app lo cual quien me a estado robando  desde el año 2009 que fue cuando se usó toda la tecnología que cree para hacer un realiti show en eu  y nuncae pago robo y se fue ahora el tiempo dará rodo

2024-01-21 20:12 UTC, sennhann29 commented on README.md
896032

2024-01-21 20:12 UTC, sennhann29 commented on README.md
> -## W3C website
896032

2024-01-25 06:16 UTC, Desmondpsg1976 commented on README.md
> +We welcome feedback from the community. You can submit feedback or issues via GitHub or  email.
My phone scammer help